### PR TITLE
Fix auto deploy on Travis CI

### PR DESCRIPTION
**Pull request by zhusee2**
1. Prevent publishing canary builds on `master`
2. Checkout to `master` before running `lerna publish` script

### CODE REVIEW

**Comment by zhusee2** [comment]
I assume not because it can run `git checkout -qf [commit-hash]` work on given commit.

**Comment by zhusee2** [comment]
hmm you're right. Let me check for that

**Comment by zhusee2** [comment]
啊忘記 checkout to master = =

**Comment by cjies** [comment]
Just fix that line in master XD

**Pull request merged**
