### PR TITLE
Fix Travis npm integration (take 2)

### PR DESCRIPTION
**Pull request by zhusee2**

### CODE REVIEW

**Comment by cjies** [comment]
May try to add `set -e` in the front of `before_scripts`.

Check https://github.com/iCHEF/gypcrete/issues/85#issuecomment-336069898

**Comment by zhusee2** [comment]
Trying the `npm config` approach. Will see if it works after it merges.

**Comment by zhusee2** [comment]
No sadly it didn't work.
https://travis-ci.org/iCHEF/gypcrete/builds/286960913

```
855 $ npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
858 The command "npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}" exited with 0.

882 lerna ERR! publish npm ERR! code ENEEDAUTH
883 lerna ERR! publish npm ERR! need auth auth required for publishing
884 lerna ERR! publish npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by zhusee2** [comment]
It's weird enough that the `npm config` trick does seem to work here:
https://travis-ci.org/iCHEF/gypcrete/builds/287353305#L733

```
725 $ npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
726
727 $ npm whoami
728 ichefbot
729
730 $ cd packages/core
731
732 $ npm whoami
733 ichefbot
```

**Comment by cjies** [comment]
You meet the same problem that I met before XD

https://github.com/iCHEF/gypcrete/pull/68/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R104

**Comment by zhusee2** [comment]
OK problem solved: the default NPM registry on Travis CI is somehow incorrect.
Specify registry manually solves this problem.

**Comment by cjies** [comment]
Note the problem here that I met before XD
https://github.com/iCHEF/gypcrete/pull/68/commits/03d1916c7d173f83e0229854ef94d6f7dbb47e9c

**Pull request merged**
